name: Community Engagement

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  discussion:
    types: [created]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome New Contributors
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thanks for opening your first issue! The community will review it soon."
          pr-message: "🎉 Thanks for your first PR! Someone will review it shortly."

  add-badges:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
      - name: Add Contributor Badge
        uses: actions/github-script@v6
        with:
          script: |
            const contributor = context.payload.sender.login;
            // Add logic to update contributor badge
